// Matrix Rain Effect
const canvas = document.getElementById('matrixCanvas');
const ctx = canvas.getContext('2d');
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

const fontSize = 16;
const columns = canvas.width / fontSize;
const drops = Array(Math.floor(columns)).fill(1);
const matrixChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

function drawMatrixRain() {
    ctx.fillStyle = "rgba(0, 0, 0, 0.05)";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#0F0";
    ctx.font = `${fontSize}px monospace`;

    for (let i = 0; i < drops.length; i++) {
        const char = matrixChars[Math.floor(Math.random() * matrixChars.length)];
        ctx.fillText(char, i * fontSize, drops[i] * fontSize);

        if (drops[i] * fontSize > canvas.height && Math.random() > 0.975) {
            drops[i] = 0;
        }
        drops[i]++;
    }
}

setInterval(drawMatrixRain, 50);

window.addEventListener('resize', () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
});

// Typing effect function
function showTypingEffect() {
    const typingIndicator = document.getElementById('typingIndicator');
    if (document.getElementById('search').value.length > 0) {
        typingIndicator.classList.remove('hidden');
    } else {
        typingIndicator.classList.add('hidden');
    }
}

// Generated by Copilot
const searchInput = document.getElementById('search-bar');

searchInput.addEventListener('focus', function() {
    this.style.caretColor = 'red'; // Changes the cursor color when focused
});

// Function to set active link in the navbar
function setActiveLink(link) {
    const navLinks = document.querySelectorAll('.nav-link');
    navLinks.forEach(navLink => {
        navLink.classList.remove('active');
    });
    link.classList.add('active');
}

// Smooth scrolling for anchor links
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();
        document.querySelector(this.getAttribute('href')).scrollIntoView({
            behavior: 'smooth'
        });
    });
});

// Blinking Title Functionality
let originalTitle = document.title;
let isBlinking = true;

function blinkTitle() {
    if (isBlinking) {
        document.title = document.title === originalTitle ? "BLINK ME" : originalTitle;
    }
}

// Start blinking the title
setInterval(blinkTitle, 1000); // Change title every second

// Typing Indicator (Optional)
const typingIndicator = document.getElementById('typingIndicator');

// Function to show typing indicator
function showTypingIndicator() {
    typingIndicator.classList.remove('hidden');
}

// Function to hide typing indicator
function hideTypingIndicator() {
    typingIndicator.classList.add('hidden');
}

// Example usage of typing indicator (you can customize this)
document.querySelector('form').addEventListener('submit', function() {
    showTypingIndicator();
    setTimeout(hideTypingIndicator, 3000); // Hide after 3 seconds (simulate typing)
});