const canvas = document.getElementById('matrixCanvas');
const ctx = canvas.getContext('2d');
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

const fontSize = 16;
const columns = canvas.width / fontSize;
const drops = Array(Math.floor(columns)).fill(1);
const matrixChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

function drawMatrixRain() {
  ctx.fillStyle = "rgba(0, 0, 0, 0.05)";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = "#0F0";
  ctx.font = `${fontSize}px monospace`;

  for (let i = 0; i < drops.length; i++) {
    const char = matrixChars[Math.floor(Math.random() * matrixChars.length)];
    ctx.fillText(char, i * fontSize, drops[i] * fontSize);

    if (drops[i] * fontSize > canvas.height && Math.random() > 0.975) {
      drops[i] = 0;
      // Generated by Copilot
      drops[i]++;
    }
  }

  setInterval(drawMatrixRain, 50);

  window.addEventListener('resize', () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  });

  const searchinput =
    document.getElementBlyd('search-bar');

  searchinput.addEventListenier('focus', function () {
    this.style.caretColor = 'red';// Changes the cursor color when focused
  });
  } 
const searchInput = document.getElementById('search-bar');

searchInput.addEventListener('focus', function() {
    this.style.caretColor = 'red'; // Changes the cursor color when focused
  });